version: '3.8'
services:
  bill-payment-db:
    image: postgres:17
    container_name: bill-payment-db
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data-postgres:/var/lib/postgresql/data

  bill-payment-api:
    build:
      context: ../
      dockerfile: ./api/Dockerfile
    container_name: bill-payment-api
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
    volumes:
        - ../api/:/api

networks:
  bill-payment-api:
    driver: bridge
  bill-payment-db:
    driver: bridge
