version: '3.8'
services:
  bill-payment-api:
    build:
      context: ../
      dockerfile: ./api/Dockerfile
    container_name: bill-payment-api
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9229:9229"
      - "4001:4001"
    networks:
      - bill-payment-api
      - bill-payment-db
    depends_on:
      - bill-payment-db
    restart: unless-stopped
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
    volumes:
        - ../api/:/api

networks:
  bill-payment-api:
    driver: bridge
