version: '3.8'
services:
  db:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  api:
    build:
      context: ../api
    container_name: api_service
    ports:
      - "${PORT}:4001"
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_URL: ${DB_URL}
      NODE_ENV: ${NODE_ENV}
