FROM node:22.11

RUN npm i concurrently nodemon -g

ADD ./api ./api
WORKDIR /api
COPY ./api .
RUN npm install
RUN npm link
EXPOSE 4001

CMD ["sh", "-c", "npx sequelize-cli db:migrate && npm run dev"]
